# coding: utf-8

# flake8: noqa
"""
    Timeular Public API

     Welcome to the documentation of Timeular Public API v1.  You can try all requests here, in documentation, with use of `Try it out` button (available in each endpoint description after folding it out).  Most of endpoints are secured. In order to access them you have to provide *Access Token*. To do so, click on `Authorize` button below and provide `Bearer <your_access_token>` as a value for `Authorization` request header. To obtain *Access Token* you have to sign-in with pair of *API Key* and *API Secret* first. API Key & API Secret can be generated on [Profile website](https://profile.timeular.com/#/app/) or, if you have Access Token already, with `POST` request to `/developer/api-access`.  **Warning:** authentication flow may change soon due to active development of Timeular and its API.  If you have any questions, please visit [Support page](http://support.timeular.com) and ask them there.  Happy API browsing!  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.activities_configuration_response import ActivitiesConfigurationResponse
from swagger_client.models.activity_configuration_response import ActivityConfigurationResponse
from swagger_client.models.activity_creation_request import ActivityCreationRequest
from swagger_client.models.activity_edition_request import ActivityEditionRequest
from swagger_client.models.archived_activities_response import ArchivedActivitiesResponse
from swagger_client.models.archived_activity_response import ArchivedActivityResponse
from swagger_client.models.current_tracking_response import CurrentTrackingResponse
from swagger_client.models.developer_api_access_response import DeveloperApiAccessResponse
from swagger_client.models.developer_full_api_access_response import DeveloperFullApiAccessResponse
from swagger_client.models.developer_sign_in_request import DeveloperSignInRequest
from swagger_client.models.developer_sign_in_response import DeveloperSignInResponse
from swagger_client.models.device_edition_request import DeviceEditionRequest
from swagger_client.models.device_response import DeviceResponse
from swagger_client.models.devices_response import DevicesResponse
from swagger_client.models.edit_tracking_request import EditTrackingRequest
from swagger_client.models.edit_tracking_response import EditTrackingResponse
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.integrations_response import IntegrationsResponse
from swagger_client.models.mention_response import MentionResponse
from swagger_client.models.profile_response import ProfileResponse
from swagger_client.models.start_tracking_request import StartTrackingRequest
from swagger_client.models.started_tracking_response import StartedTrackingResponse
from swagger_client.models.stop_tracking_request import StopTrackingRequest
from swagger_client.models.stopped_tracking_response import StoppedTrackingResponse
from swagger_client.models.success_with_ignored_errors_response import SuccessWithIgnoredErrorsResponse
from swagger_client.models.tag_response import TagResponse
from swagger_client.models.tags_and_mentions_response import TagsAndMentionsResponse
from swagger_client.models.time_entries_response import TimeEntriesResponse
from swagger_client.models.time_entry_activity_response import TimeEntryActivityResponse
from swagger_client.models.time_entry_creation_request import TimeEntryCreationRequest
from swagger_client.models.time_entry_duration_response import TimeEntryDurationResponse
from swagger_client.models.time_entry_edition_request import TimeEntryEditionRequest
from swagger_client.models.time_entry_response import TimeEntryResponse
from swagger_client.models.tracking_activity_response import TrackingActivityResponse
from swagger_client.models.tracking_response import TrackingResponse
